# Generated by Django 3.0 on 2019-12-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('published', 'Published'), ('unpublished', 'Unpublished')], default='pending_approval', max_length=16),
        ),
    ]
