# Generated by Django 3.0 on 2019-12-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191208_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('publish_without_moderation', 'Can publish without moderation')]},
        ),
    ]
